language: python
python:
  - 2.7
sudo: required
dist: jessie

before_script:
  - sleep 3

script:
- ls

notifications:
  email:
    recipients:
    - stefan.zweig@gmail.com
    on_success: always
    on_failure: always
    
after_success:
- echo Good.\n
